apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartnotes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartnotes-api
  template:
    metadata:
      labels:
        app: smartnotes-api
    spec:
      containers:
      - name: smartnotes-api
        image: smartnotesacr.azurecr.io/smartnotes-api:v3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: smartnotes-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: smartnotes-api
